# Generated by Django 4.2.17 on 2024-12-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
