# Generated by Django 5.0.4 on 2024-04-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cartitem_cart_alter_cartitem_unique_together'),
        ('api', '0003_alter_uuid_cart'),
    ]

    operations = [
    ]
