# Generated by Django 5.0.4 on 2024-04-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
