# Generated by Django 5.0.4 on 2024-04-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creator',
        ),
    ]
