FROM python:3.10.6-slim-buster

WORKDIR /backend
ADD . /backend/
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /backend

CMD [ "python3","manage.py", "runserver", "0.0.0.0:8000"]